---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "load_tests_springboot"
  name: "load-tests-springboot-svc"
spec:
  ports:
  - name: "port-1-load-tes"
    port: 9092
    protocol: "TCP"
    targetPort: 9092
  selector:
    app: "load_tests_springboot"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "load_tests_springboot"
  name: "load-tests-springboot-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "load_tests_springboot"
  template:
    metadata:
      labels:
        app: "load_tests_springboot"
    spec:
      containers:
      - env:
        - name: "SQL_URL"
          value: "jdbc:mysql://mysql8-service:3306/spring_hospital"
        image: "hasathcharu/balpersist_load_tests:springboot_v1"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "load-tests-springboot-deployment"
        ports:
        - containerPort: 9092
          name: "port-1-load-tes"
          protocol: "TCP"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "load_tests_springboot"
  name: "load-tests-hpa"
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: "cpu"
      target:
        averageUtilization: 50
        type: "Utilization"
    type: "Resource"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "load-tests-springboot-deployment"
