---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "load_tests"
  name: "load-tests-svc"
spec:
  ports:
  - name: "port-1-load-tes"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: "load_tests"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
data:
  Config.toml: "[load_tests.db]\nhost = \"mysql8-service\"\nport = 3306\nuser = \"root\"\
    \npassword = \"Test123#\"\ndatabase = \"hospital\"\n\n"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "load_tests"
  name: "load-tests-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "load_tests"
  template:
    metadata:
      labels:
        app: "load_tests"
    spec:
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        image: "hasathcharuwso2/load_tests:persist_v1"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "load-tests-deployment"
        ports:
        - containerPort: 9090
          name: "port-1-load-tes"
          protocol: "TCP"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "config-config-map-volume"
          readOnly: false
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "load_tests"
  name: "load-tests-hpa"
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: "cpu"
      target:
        averageUtilization: 50
        type: "Utilization"
    type: "Resource"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "load-tests-deployment"
