[container.image]
repository = "hasathcharuwso2"
name = "load_tests"
tag = "mysql_v1"

[cloud.deployment]
min_memory = "256Mi"
max_memory = "512Mi"
min_cpu = "200m"
max_cpu="1000m"

[cloud.deployment.autoscaling]
min_replicas = 1
max_replicas = 1

[[cloud.config.files]]
file="Config.toml"
